### ISSUE TITLE
add flag to optionally generate structured output

### ISSUE THREAD

**Issue by tomreitz** [edanalytics/earthmover#30]
To use earthmover in an automated data pipeline it would be useful to have it generate structured output noting how many rows it processed for each destination, the run timestamp, and possibly other information. Open questions include:
1. what should the flag be? perhaps `--results-file output.json`
2. what should the output format be? (YAML, JSON, something else?)
3. besides the items noted above, what else should be included in the results

Tagging @jayckaiser for thoughts.

**Comment by tomreitz** [comment]
Based on our conversation today, I'm proposing that
* `earthmover`'s structured output is enabled with a cli flag `--results-file ./results.json`
* output format is JSON, like this:
   ```json
   {
     "timestamp": "2023-05-15 02:03:11Z00",
     "output_dir": "/path/to/some/dir/",
     "row_counts": {
       "$sources.enrollments": 120,
       "$transformations.enrollments_cleaned": 117,
       "$transformations.enrollments_deduplicated": 100,
       "$destinations.studentSchoolAssociations": 100
     }
  }
   ```
  where only nodes defined with `structured_output: True` are included in `row_counts`, and the value is the number of rows in the dataframe *after it has been processed* - so for sources, after they're loaded; for transformations, after their operation(s) have been run; for destinations, the size of the `source` dataframe.

We also discussed the exit codes `earthmover` should return in different circumstances, to trigger the AirFlow BashOperator task to raise an `AirflowSkipException` or `AirflowException` (per [the Airflow docs](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/bash/index.html)). Is it correct that
1. if earthmover skips running because no input hashes have changed since the last run, should it return exit code 99? (so the Airflow task skips)
2. if any earthmover source fails a defined `expect`ation should return exit code 1? (so the Airflow task fails)

**Comment by jayckaiser** [comment]
A couple thoughts:

- We may want to rename `timestamp` to `started_at` or `completed_at` or something of that nature. `timestamp` is already too prolific in the namespace.
- I agree that having a built-in exit-code skip return is a good idea. We can also define our own `skip_exit_code` in the operator to use a different one. I'll want to make sure the exit-code returned is generic and not solely designed around Airflow specifications. Exit code 99 means `Cannot assign requested address`, which may be confusing to those using Earthmover outside of Airflow. Alternatives may be 17 (`File exists`) or 42 (`No message of desired type`), but I'm open to suggestions or pushback.
- I think it would be worthwhile to track total run-time of the script. We could include a field `runtime_sec` or something similar to display this.
- Other potentially-interesting information: the number of sources, transformations, and destinations run; the command used to trigger the run.

**Comment by tomreitz** [comment]
Closing this issue as it was implemented in [this PR](https://github.com/edanalytics/earthmover/pull/35).
