### ISSUE TITLE
Query for filter_rows operation does not work as expected

### ISSUE THREAD

**Issue by emondal1026** [edanalytics/earthmover#57]
Here is the code snippet:

transformations:
  descriptors:
    source: $sources.file_in
    operations:
      - operation: filter_rows
        query: codevalue != "N/A"
        behavior: include
        
 I would expect the output to include rows that do not have "N/A" as a value for the `codevalue`  instead the output includes these rows:
 { 'codeValue': "N/A", 'description': "N/A", 'shortDescription': "N/A", 'namespace': "uri://jeffco.org/StaffIdentificationSystemDescriptor" }

template used:
{
    'codeValue': "{{ codevalue }}",
    'description': "{{ description }}",
    'shortDescription': "{{ shortdescription }}",
    'namespace': "{{ namespace }}"
}

When I load the source file as a data frame and run pandas query on its own as such:

    descriptors = pd.read_csv(in_file_path, encoding='utf-8')
    # subset columns and create json
    full_descriptors = []
    descriptors = descriptors.dropna(subset=['codevalue'])
    descriptors = descriptors.query('codevalue != "N/A"', engine='python')

output is as expected without rows for "N/A" codevalues.

There is no error thrown when earthmover processes the above template and config file. Please let me know if I can provide any more detail! I do have another example that does error on perhaps a slightly more complicated query, that error is saying that it cannot find a key being asked for.  I can open another issue for that if needed. Thank you!

I don't know how to format things on github so sorry for the misformatted code!

**Comment by jayckaiser** [comment]
This ended up being an issue involving null datatypes. The "N/A" representation is not a string but a Pandas NA. To remove them using query, use `codevalue.notnull()`.
