### ISSUE TITLE
DistinctRowsOperation is missing option for row-sorting

### ISSUE THREAD

**Issue by rlittle08** [edanalytics/earthmover#60]
It would be helpful to allow a sort on columns before dropping duplicates. For example, sort on latest timestamp to keep only a corrected record.

From short research, I realize this may be difficult to achieve in dask?

Priority for this is low, because in many of our cases we want to keep both records if they have a substantive difference.

**Comment by jayckaiser** [comment]
We added a `SortRowsOperation` in Earthmover 0.2.1 that can be used in front of a `DistinctRowsOperation`.
